apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: drone-management
type: Opaque
data:
  # These values should be base64 encoded
  database-url: postgresql://postgres:postgres@postgres-service:5432/auth_db
  postgres-user: cG9zdGdyZXM=  # postgres
  postgres-password: cG9zdGdyZXM=  # postgres
  postgres-db: YXV0aF9kYg==  # auth_db
  jwt-secret: your-jwt-secret-here
  redis-password: your-redis-password-here 